apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-coder-app
  labels:
    app: llama-coder-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llama-coder-app
  template:
    metadata:
      labels:
        app: llama-coder-app
    spec:
      containers:
      - name: llama-coder-app
        image: demonstrationorg/llama-coder-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10