apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-coder
  labels:
    app: llama-coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-coder
  template:
    metadata:
      labels:
        app: llama-coder
    spec:
      containers:
      - name: llama-coder
        image: llama-coder:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10