apiVersion: v1
kind: Service
metadata:
  name: llama-coder-app
  labels:
    app: llama-coder-app
spec:
  selector:
    app: llama-coder-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP