apiVersion: v1
kind: Service
metadata:
  name: llama-coder-app
  labels:
    app: llama-coder
spec:
  selector:
    app: llama-coder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP